-- MySQL Script generated by MySQL Workbench
-- Thu Mar 15 20:05:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TeacherAssistant
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TeacherAssistant
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TeacherAssistant` DEFAULT CHARACTER SET utf8 ;
USE `TeacherAssistant` ;

-- -----------------------------------------------------
-- Table `TeacherAssistant`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TeacherAssistant`.`alumnos` (
  `id_alumno` INT NOT NULL AUTO_INCREMENT,
  `nombre_alumno` VARCHAR(45) NULL,
  `apellido_alumno` VARCHAR(60) NULL,
  `ci_alumno` INT NULL,
  `estado_alumno` VARCHAR(20) NULL,
  PRIMARY KEY (`id_alumno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TeacherAssistant`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TeacherAssistant`.`docente` (
  `id_docente` INT NOT NULL AUTO_INCREMENT,
  `nombre_docente` VARCHAR(45) NULL,
  `apellido_docente` VARCHAR(60) NULL,
  `password_docente` VARCHAR(45) NULL,
  `estado_docente` VARCHAR(20) NULL,
  PRIMARY KEY (`id_docente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TeacherAssistant`.`tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TeacherAssistant`.`tarea` (
  `id_tarea` INT NOT NULL AUTO_INCREMENT,
  `nombre_tarea` VARCHAR(150) NULL,
  `descripcion_tarea` VARCHAR(300) NULL,
  `estado_tarea` VARCHAR(45) NULL,
  `fechainicio_tarea` DATE NULL,
  `fechafin_tarea` DATE NULL,
  PRIMARY KEY (`id_tarea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TeacherAssistant`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TeacherAssistant`.`grupo` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `nombre_grupo` VARCHAR(45) NULL,
  `estado_grupo` VARCHAR(45) NULL,
  `alumnos_id_alumno` INT NOT NULL,
  `tarea_id_tarea` INT NOT NULL,
  PRIMARY KEY (`id_grupo`),
  INDEX `fk_grupo_alumnos_idx` (`alumnos_id_alumno` ASC),
  INDEX `fk_grupo_tarea1_idx` (`tarea_id_tarea` ASC),
  CONSTRAINT `fk_grupo_alumnos`
    FOREIGN KEY (`alumnos_id_alumno`)
    REFERENCES `TeacherAssistant`.`alumnos` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_tarea1`
    FOREIGN KEY (`tarea_id_tarea`)
    REFERENCES `TeacherAssistant`.`tarea` (`id_tarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TeacherAssistant`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TeacherAssistant`.`curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nombre_curso` VARCHAR(45) NULL,
  `estado_curso` VARCHAR(45) NULL,
  `alumnos_id_alumno` INT NOT NULL,
  `docente_id_docente` INT NOT NULL,
  PRIMARY KEY (`id_curso`),
  INDEX `fk_curso_alumnos1_idx` (`alumnos_id_alumno` ASC),
  INDEX `fk_curso_docente1_idx` (`docente_id_docente` ASC),
  CONSTRAINT `fk_curso_alumnos1`
    FOREIGN KEY (`alumnos_id_alumno`)
    REFERENCES `TeacherAssistant`.`alumnos` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_docente1`
    FOREIGN KEY (`docente_id_docente`)
    REFERENCES `TeacherAssistant`.`docente` (`id_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
